/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Chimp;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Pratik Kapoor
 */
public class qlist extends javax.swing.JPanel {

    /**
     * Creates new form qlist
     */
            Connection conn=null;
    final String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
    final String DB_URL = "jdbc:mysql://localhost:3306/surveychimp";
    final String user="root";
    final String pass="admin";  
    ResultSet check = null;
    ResultSet check2 = null;
    int flag = 0;
    
    String q_id, question, username;
    
    /*public qlist() {
        initComponents();
    }*/
    
    public qlist(String q_id, String question, String user)
    {
        initComponents();
        this.q_id = q_id;
        this.question = question;
        jLabel1.setText(question);
        this.q_id = q_id;
        this.username = user;
    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        setMaximumSize(new java.awt.Dimension(330, 32767));
        setMinimumSize(new java.awt.Dimension(330, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        
        try
        {
        Class.forName(JDBC_DRIVER);
                    System.out.println("Connecting");
                    conn=(Connection) DriverManager.getConnection(DB_URL,user,pass);
                    System.out.println("Conection Success");
                    Statement stmt=null;
                    stmt=(Statement) conn.createStatement();
        
                    String prevans = "select username, q_id from answer;";
                    check= stmt.executeQuery(prevans);
                    
                    Statement stmt2=null;
                    stmt2=(Statement) conn.createStatement();
                    String query = "select username from question where q_id='"+q_id+"';";
                    check2= stmt2.executeQuery(query);
                    
                    while(check.next())
                    {
                        if(check.getString("username").equals(username) && check.getString("q_id").equals(q_id))
                        {
                            flag = 1;
                        }
                    }
                    
                    while(check2.next())
                    {
                        if(check2.getString("username").equals(username))
                        {
                            flag = 2;
                        }
                    }
        }
        
        catch(Exception e)
        {
            System.out.println(e);
        }
        
        if(flag==0)
        {
            answerq obj = new answerq();
            obj.getid(q_id, username);
            obj.setVisible(true);
            this.setVisible(false);
        }
        
        else if(flag==1)
        {
            JOptionPane.showMessageDialog(null,"Question Already Answered. View Results.","Skip to Results",JOptionPane.WARNING_MESSAGE);
            
            Results result = new Results();
            result.setVisible(true);
            result.init(username, q_id);
            this.setVisible(false);
        }
        
        else if(flag==2)
        {
            JOptionPane.showMessageDialog(null,"Questions asked by self cannot be answered","Skip to Results",JOptionPane.WARNING_MESSAGE);
            
            Results result = new Results();
            result.setVisible(true);
            result.init(username, q_id);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
